name: Dependency Updates

on:
  schedule:
    # Run weekly on Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Update frontend dependencies
    - name: Update frontend dependencies
      working-directory: ./frontend
      run: |
        npm update
        npm audit fix --audit-level=moderate || true

    # Update infrastructure dependencies
    - name: Update infrastructure dependencies
      working-directory: ./infrastructure
      run: |
        npm update
        npm audit fix --audit-level=moderate || true

    # Update Python dependencies
    - name: Update Python dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade -r requirements.txt

    # Check for security vulnerabilities
    - name: Security audit frontend
      working-directory: ./frontend
      run: |
        npm audit --audit-level=moderate || echo "Security issues found, but continuing..."

    - name: Security audit infrastructure
      working-directory: ./infrastructure
      run: |
        npm audit --audit-level=moderate || echo "Security issues found, but continuing..."

    # Create pull request if there are changes
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: '🤖 Automated dependency updates'
        body: |
          ## 🤖 Automated Dependency Updates
          
          This PR contains automated dependency updates to keep the project secure and up-to-date.
          
          ### Changes Made:
          - Updated frontend dependencies (npm packages)
          - Updated infrastructure dependencies (npm packages)
          - Updated Python dependencies
          
          ### Security Audit:
          - Frontend: npm audit completed
          - Infrastructure: npm audit completed
          
          ### Next Steps:
          - [ ] Review the changes
          - [ ] Run tests locally
          - [ ] Deploy to development environment
          - [ ] Merge if everything looks good
          
          ---
          *This PR was automatically generated by GitHub Actions*
        branch: dependency-updates
        delete-branch: true
        labels: |
          dependencies
          automated
          security 